# Assignment 3 (Solution)

In [1]:
import pandas as pd
import numpy as np

# Load MovieLens 100K dataset into a dataframe of pandas
names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('ml-100k/u.data', sep='\t', names=names)
df.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [2]:
# Select 500 most active users and 500 most active items from the dataset
n_most_active_users = 500
n_most_active_items = 500

user_ids = df.groupby('user_id').count().sort_values(by='rating', ascending=False).head(n_most_active_users).index
item_ids = df.groupby('item_id').count().sort_values(by='rating', ascending=False).head(n_most_active_items).index
df = df[(df['user_id'].isin(user_ids)) & (df['item_id'].isin(item_ids))]

In [3]:
# Map new internal ID for items
i_ids = df['item_id'].unique().tolist()
item_dict = dict(zip(i_ids, [i for i in range(len(i_ids))]))
df['item_id'] = df['item_id'].map(item_dict)

# Split Dataset

In [4]:
# The number of training users and active users
n_training_users = 300
n_active_users = n_most_active_users - n_training_users

# The number of GIVEN ratings for active users
GIVEN = 20

# Randomly select users from the most active users as training set
random_uids = np.random.choice(df.user_id.unique(), n_training_users, replace=False)
train_df = df[df['user_id'].isin(random_uids)]
# Map new internal ID for all users in the training set
u_ids = train_df['user_id'].unique().tolist()
user_dict = dict(zip(u_ids, [i for i in range(len(u_ids))]))
train_df['user_id'] = train_df['user_id'].map(user_dict)

# The rest of users are active users for testing
remain_df = df[~df['user_id'].isin(random_uids)]
# Map new internal ID for all active users
u_ids = remain_df['user_id'].unique().tolist()
user_dict = dict(zip(u_ids, [i for i in range(len(u_ids))]))
remain_df['user_id'] = remain_df['user_id'].map(user_dict)

# Randomly select GIVEN ratings for active users
active_df = remain_df.groupby('user_id').sample(n=GIVEN, random_state=1024)

test_df = remain_df[~remain_df.index.isin(active_df.index)]

<ipython-input-4-fb140fbf3b12>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['user_id'] = train_df['user_id'].map(user_dict)
<ipython-input-4-fb140fbf3b12>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remain_df['user_id'] = remain_df['user_id'].map(user_dict)

In [5]:
# Convert the format of datasets to matrices
df_zeros = pd.DataFrame({'user_id': np.tile(np.arange(0, n_training_users), n_most_active_items), 'item_id': np.repeat(np.arange(0, n_most_active_items), n_training_users), 'rating': 0})
train_ds = df_zeros.merge(train_df, how='left', on=['user_id', 'item_id']).fillna(0.).pivot_table(values='rating_y', index='user_id', columns='item_id')

df_zeros = pd.DataFrame({'user_id': np.tile(np.arange(0, n_active_users), n_most_active_items), 'item_id': np.repeat(np.arange(0, n_most_active_items), n_active_users), 'rating': 0})
active_ds = df_zeros.merge(active_df, how='left', on=['user_id', 'item_id']).fillna(0.).pivot_table(values='rating_y', index='user_id', columns='item_id')
test_ds = df_zeros.merge(test_df, how='left', on=['user_id', 'item_id']).fillna(0.).pivot_table(values='rating_y', index='user_id', columns='item_id')

train_ds, active_ds, test_ds

(item_id  0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
 user_id                                                    ...
 0        3.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  0.0
 1        0.0  2.0  0.0  4.0  0.0  4.0  4.0  0.0  0.0  2.0  ...  0.0  4.0  4.0
 2        0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  4.0  ...  0.0  0.0  0.0
 3        4.0  0.0  5.0  0.0  0.0  3.0  4.0  2.0  0.0  2.0  ...  0.0  2.0  0.0
 4        4.0  0.0  5.0  0.0  1.0  0.0  3.0  2.0  0.0  0.0  ...  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
 295      0.0  0.0  5.0  4.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0
 296      4.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 297      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  3.0  4.0  0.0
 298      0.0  0.0  0.0  3.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  5.0
 299      0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  3.0  0.0  ...  4.0  0.0  0.0

 item_id  493  494  495  496  497  498  499
 user_id
 0        0.0  0.0  0.0  4.0  0.0  3.0  0.0
 1        0.0  3.0  3.0  0.0  0.0  0.0  0.0
 2        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3        0.0  0.0  0.0  0.0  4.0  0.0  0.0
 4        4.0  1.0  0.0  0.0  0.0  0.0  2.0
 ...      ...  ...  ...  ...  ...  ...  ...
 295      0.0  0.0  0.0  0.0  0.0  1.0  0.0
 296      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 297      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 298      0.0  0.0  3.0  0.0  0.0  0.0  0.0
 299      5.0  0.0  0.0  3.0  0.0  0.0  0.0

 [300 rows x 500 columns],
 item_id  0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
 user_id                                                    ...
 0        0.0  0.0  4.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  0.0
 1        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  5.0  ...  0.0  0.0  0.0
 3        0.0  4.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
 195      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  ...  4.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  4.0
 198      0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  4.0  0.0  ...  0.0  0.0  0.0
 199      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

 item_id  493  494  495  496  497  498  499
 user_id
 0        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 2        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...
 195      0.0  0.0  0.0  0.0  5.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 198      0.0  4.0  2.0  3.0  0.0  0.0  0.0
 199      0.0  0.0  0.0  0.0  0.0  0.0  0.0

 [200 rows x 500 columns],
 item_id  0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
 user_id                                                    ...
 0        0.0  0.0  0.0  4.0  4.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 1        0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
 2        3.0  0.0  4.0  0.0  0.0  3.0  2.0  0.0  0.0  0.0  ...  0.0  4.0  0.0
 3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  ...  0.0  0.0  3.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  4.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
 195      0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  ...  0.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  3.0  5.0  ...  0.0  0.0  0.0
 197      4.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  ...  0.0  0.0  0.0
 198      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  4.0
 199      0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

 item_id  493  494  495  496  497  498  499
 user_id
 0        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 2        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4        0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ...      ...  ...  ...  ...  ...  ...  ...
 195      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 196      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 197      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 198      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 199      0.0  0.0  0.0  0.0  0.0  0.0  0.0

 [200 rows x 500 columns])

# Algorithm that you need to implement

In [6]:
## Put all your implementation for your algorithm in this cell only to handle the missing values; 
## and please DO NOT change anything in the rest of the cells in this framework. 

## Note: 
## The user-item rating matrix is train_ds, and the missing values are those 0s in train_ds. 

## The following parameters are required in the given report "", please do not change them. 
LAMBDA = 0.7    # λ
GAMMA = 10      # γ
DELTA = 10      # δ
ITA = 0.7       # η
THETA = 0.7     # θ
EPSILON = 1e-9

# Compute Pearson Correlation Coefficient for All Pairs of Users in training set
user_pearson_corr = np.zeros((train_ds.shape[0], train_ds.shape[0]))

for i, user_i_vec in enumerate(train_ds.values):
    for j, user_j_vec in enumerate(train_ds.values):

        if i == j:
            continue

        # ratings corated by the current pair od users
        mask_i = user_i_vec > 0
        mask_j = user_j_vec > 0

        # corrated item index, skip if there are no corrated ratings
        corrated_index = np.intersect1d(np.where(mask_i), np.where(mask_j))
        if len(corrated_index) == 0:
            continue

        # average value of user_i_vec and user_j_vec
        mean_user_i = np.sum(user_i_vec) / (np.sum(np.clip(user_i_vec, 0, 1)) + EPSILON)
        mean_user_j = np.sum(user_j_vec) / (np.sum(np.clip(user_j_vec, 0, 1)) + EPSILON)

        # compute pearson corr
        user_i_sub_mean = user_i_vec[corrated_index] - mean_user_i
        user_j_sub_mean = user_j_vec[corrated_index] - mean_user_j

        r_ui_sub_r_i_sq = np.square(user_i_sub_mean)
        r_uj_sub_r_j_sq = np.square(user_j_sub_mean)

        r_ui_sum_sqrt = np.sqrt(np.sum(r_ui_sub_r_i_sq))
        r_uj_sum_sqrt = np.sqrt(np.sum(r_uj_sub_r_j_sq))

        sim = np.sum(user_i_sub_mean * user_j_sub_mean) / (r_ui_sum_sqrt * r_uj_sum_sqrt + EPSILON)

        # significance weighting
        weighted_sim = (min(len(corrated_index), GAMMA) / GAMMA) * sim

        user_pearson_corr[i][j] = weighted_sim


# Compute Pearson Correlation Coefficient for All Pairs of Items in training set
item_pearson_corr = np.zeros((train_ds.shape[1], train_ds.shape[1]))

for i, item_i_vec in enumerate(train_ds.T.values):
    for j, item_j_vec in enumerate(train_ds.T.values):

        if i == j:
            continue

        # ratings corated by the current pair od items
        mask_i = item_i_vec > 0
        mask_j = item_j_vec > 0

        # corrated index, skip if there are no corrated ratings
        corrated_index = np.intersect1d(np.where(mask_i), np.where(mask_j))
        if len(corrated_index) == 0:
            continue

        # average value of item_i_vec and item_j_vec
        mean_item_i = np.sum(item_i_vec) / (np.sum(np.clip(item_i_vec, 0, 1)) + EPSILON)
        mean_item_j = np.sum(item_j_vec) / (np.sum(np.clip(item_j_vec, 0, 1)) + EPSILON)

        # compute pearson corr
        item_i_sub_mean = item_i_vec[corrated_index] - mean_item_i
        item_j_sub_mean = item_j_vec[corrated_index] - mean_item_j

        r_ui_sub_ri_sq = np.square(item_i_sub_mean)
        r_uj_sub_rj_sq = np.square(item_j_sub_mean)

        r_ui_sub_ri_sq_sum_sqrt = np.sqrt(np.sum(r_ui_sub_ri_sq))
        r_uj_sub_rj_sq_sum_sqrt = np.sqrt(np.sum(r_uj_sub_rj_sq))

        sim = np.sum(item_i_sub_mean * item_j_sub_mean) / (r_ui_sub_ri_sq_sum_sqrt * r_uj_sub_rj_sq_sum_sqrt + EPSILON)

        # significance weighting
        weighted_sim = (min(len(corrated_index), DELTA) / DELTA) * sim

        item_pearson_corr[i][j] = weighted_sim


# Predicting All Missing Data in training set
imputed_train_ds = train_ds.values.copy()

for (i, j), rating in np.ndenumerate(train_ds.values):
    if rating > 0:
        continue
    sim_user_ids = np.where(user_pearson_corr[i] > ITA)[0]
    sim_item_ids = np.where(item_pearson_corr[j] > THETA)[0]

    if len(sim_user_ids) > 0 and len(sim_item_ids) > 0:
        #==================user-based==================#
        # the coefficient values of similar users
        sim_val = user_pearson_corr[i][sim_user_ids]

        # the average value of the current user's ratings
        sim_users = train_ds.values[sim_user_ids]
        user_mean = np.sum(train_ds.values[i]) / (np.sum(np.clip(train_ds.values[i], 0, 1)) + EPSILON)
        sim_user_mean = np.sum(sim_users, axis=1) / (np.sum(np.clip(sim_users, 0, 1), axis=1) + EPSILON)

        # select the users who rated item j
        mask_rated_j = sim_users[:, j] > 0
        
        # sim(u, v) * (r_vj - mean_v)
        sim_r_sum_mean = sim_val[mask_rated_j] * (sim_users[mask_rated_j, j] - sim_user_mean[mask_rated_j])
        
        user_based_pred = user_mean + np.sum(sim_r_sum_mean) / (np.sum(sim_val[mask_rated_j]) + EPSILON)
        user_based_pred = np.clip(user_based_pred, 0, 5)

        #==================item-based==================#
        # the coefficient values of similar items
        sim_val = item_pearson_corr[j][sim_item_ids]

        # the average value of the current item's ratings
        sim_items = train_ds.T.values[sim_item_ids]
        item_mean = np.sum(train_ds.T.values[j]) / (np.sum(np.clip(train_ds.T.values[j], 0, 1)) + EPSILON)
        sim_item_mean = np.sum(sim_items, axis=1) / (np.sum(np.clip(sim_items, 0, 1), axis=1) + EPSILON)

        # sim(u, v) * (r_v - mean_v)
        sim_r_sum_mean = sim_val * (sim_items[:, i] - sim_item_mean) 

        # filter unrated items
        w = np.clip(sim_items[:, i], 0, 1)
        sim_r_sum_mean *= w

        item_based_pred = item_mean + np.sum(sim_r_sum_mean) / (np.sum(sim_val * w) + EPSILON)    
        item_based_pred = np.clip(item_based_pred, 0, 5)

        imputed_train_ds[i][j] = LAMBDA * user_based_pred + (1 - LAMBDA) * item_based_pred

    if len(sim_user_ids) > 0 and len(sim_item_ids) == 0:
        #==================user-based==================#
        # the coefficient values of similar users
        sim_val = user_pearson_corr[i][sim_user_ids]

        # the average value of the current user's ratings
        sim_users = train_ds.values[sim_user_ids]
        user_mean = np.sum(train_ds.values[i]) / (np.sum(np.clip(train_ds.values[i], 0, 1)) + EPSILON)
        sim_user_mean = np.sum(sim_users, axis=1) / (np.sum(np.clip(sim_users, 0, 1), axis=1) + EPSILON)

        # select the users who rated item j
        mask_rated_j = sim_users[:, j] > 0
        
        # sim(u, v) * (r_vj - mean_v)
        sim_r_sum_mean = sim_val[mask_rated_j] * (sim_users[mask_rated_j, j] - sim_user_mean[mask_rated_j])
        
        user_based_pred = user_mean + np.sum(sim_r_sum_mean) / (np.sum(sim_val[mask_rated_j]) + EPSILON)
        user_based_pred = np.clip(user_based_pred, 0, 5)

        imputed_train_ds[i][j] = user_based_pred
    
    if len(sim_user_ids) == 0 and len(sim_item_ids) > 0:
        #==================item-based==================#
        # the coefficient values of similar items
        sim_val = item_pearson_corr[j][sim_item_ids]

        # the average value of the current item's ratings
        sim_items = train_ds.T.values[sim_item_ids]
        item_mean = np.sum(train_ds.T.values[j]) / (np.sum(np.clip(train_ds.T.values[j], 0, 1)) + EPSILON)
        sim_item_mean = np.sum(sim_items, axis=1) / (np.sum(np.clip(sim_items, 0, 1), axis=1) + EPSILON)

        # sim(u, v) * (r_v - mean_v)
        sim_r_sum_mean = sim_val * (sim_items[:, i] - sim_item_mean) 

        # filter unrated items
        w = np.clip(sim_items[:, i], 0, 1)
        sim_r_sum_mean *= w

        item_based_pred = item_mean + np.sum(sim_r_sum_mean) / (np.sum(sim_val * w) + EPSILON)    
        item_based_pred = np.clip(item_based_pred, 0, 5)
        
        imputed_train_ds[i][j] = item_based_pred
        
imputed_train_ds = pd.DataFrame(imputed_train_ds)
imputed_train_ds

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,3.000000,4.662227,0.000000,0.000000,3.673469,3.355769,3.810127,4.000000,0.000000,0.000000,...,2.151515,2.960000,4.824930,3.301599,3.021277,2.536585,4.000000,3.511628,3.000000,4.234734
1,4.195876,2.000000,0.000000,4.000000,3.673469,4.000000,4.000000,3.730769,0.000000,2.000000,...,2.405810,4.000000,4.000000,2.215985,3.000000,3.000000,2.117647,3.401932,0.000000,1.075670
2,4.195876,3.645833,0.000000,0.000000,5.000000,3.355769,4.962300,3.361538,0.000000,4.000000,...,1.536998,2.960000,3.785714,3.906250,3.021277,2.536585,2.117647,4.204541,0.000000,4.234734
3,4.000000,3.645833,5.000000,0.000000,3.380367,3.000000,4.000000,2.000000,0.000000,2.000000,...,2.409091,2.000000,3.785714,4.411555,2.732109,2.536585,2.117647,4.000000,0.000000,1.234734
4,4.000000,3.751096,5.000000,0.000000,1.000000,3.355769,3.000000,2.000000,0.000000,0.000000,...,2.909091,2.728116,1.786560,4.000000,1.000000,2.536585,2.117647,3.561540,0.000000,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,3.071175,2.892401,5.000000,4.000000,3.062938,1.000000,3.103935,2.931643,2.801282,1.000000,...,2.510130,2.470326,3.096612,3.132772,2.761649,2.178123,2.596192,3.014386,1.000000,2.667499
296,4.000000,3.575568,3.000000,3.545455,3.583859,4.400391,3.370508,3.490280,3.848086,3.545455,...,3.354545,3.300253,4.529375,3.653693,3.388201,3.454636,2.628954,3.559510,3.545455,3.247532
297,3.576187,1.000000,3.522727,3.522727,3.567950,3.472640,3.063493,3.436655,3.522727,3.522727,...,3.000000,4.000000,3.601623,3.637784,3.396950,3.226885,2.670352,3.455581,3.522727,3.475181
298,4.195876,1.662227,0.000000,3.000000,3.673469,3.355769,3.810127,4.000000,0.000000,0.000000,...,4.151515,2.960000,5.000000,3.215985,3.021277,3.000000,2.117647,3.511628,0.000000,2.234734
299,3.973366,3.662899,4.578749,3.878005,3.671190,3.725880,3.993776,3.000000,3.000000,2.578749,...,4.000000,3.387584,3.704863,5.000000,4.069149,3.330125,3.000000,3.950762,3.670213,3.471651

# Evaluation

### Compute Pearson Correlation Coefficient of All Pairs of Items between active set and imputed training set

In [7]:
active_item_pearson_corr = np.zeros((active_ds.shape[1], imputed_train_ds.shape[1]))

# Compute Pearson Correlation Coefficient of All Pairs of Items between active set and imputed training set
for i, item_i_vec in enumerate(active_ds.T.values):
    for j, item_j_vec in enumerate(imputed_train_ds.T.values):

        if i == j:
            continue

        # Put all your implementation for your algorithm here
        # active_item_pearson_corr[i, j] = ?

        # ratings corated by the current pair od items
        mask_i = item_i_vec > 0
        mask_j = item_j_vec > 0

        # corrated index, skip if there are no corrated ratings
        corrated_index = np.intersect1d(np.where(mask_i), np.where(mask_j))
        if len(corrated_index) == 0:
            continue

        # average value of item_i_vec and item_j_vec
        mean_item_i = np.sum(item_i_vec) / (np.sum(np.clip(item_i_vec, 0, 1)) + EPSILON)
        mean_item_j = np.sum(item_j_vec) / (np.sum(np.clip(item_j_vec, 0, 1)) + EPSILON)

        # compute pearson corr
        item_i_sub_mean = item_i_vec[corrated_index] - mean_item_i
        item_j_sub_mean = item_j_vec[corrated_index] - mean_item_j

        r_ui_sub_ri_sq = np.square(item_i_sub_mean)
        r_uj_sub_rj_sq = np.square(item_j_sub_mean)

        r_ui_sub_ri_sq_sum_sqrt = np.sqrt(np.sum(r_ui_sub_ri_sq))
        r_uj_sub_rj_sq_sum_sqrt = np.sqrt(np.sum(r_uj_sub_rj_sq))

        sim = np.sum(item_i_sub_mean * item_j_sub_mean) / (r_ui_sub_ri_sq_sum_sqrt * r_uj_sub_rj_sq_sum_sqrt + EPSILON)

        # significance weighting
        weighted_sim = (min(len(corrated_index), DELTA) / DELTA) * sim

        active_item_pearson_corr[i][j] = weighted_sim

active_item_pearson_corr

array([[ 0.        , -0.17948169,  0.15104194, ...,  0.19435053,
         0.04040134, -0.1309306 ],
       [-0.16099388,  0.        ,  0.06014257, ...,  0.21705467,
        -0.17832339, -0.20802313],
       [ 0.09329228,  0.13024273,  0.        , ...,  0.37262014,
         0.13141463,  0.07979983],
       ...,
       [ 0.12393319, -0.03409841, -0.27857546, ...,  0.        ,
        -0.20048507, -0.16496918],
       [ 0.30519705,  0.14724678,  0.42350075, ...,  0.33005785,
         0.        , -0.40839959],
       [-0.1290709 , -0.11217629,  0.19991814, ..., -0.13616363,
        -0.1       ,  0.        ]])

## Predict Ratings of Testing Set

In [8]:
test_ds_pred = np.zeros_like(test_ds.values)

K = 10

for (i, j), rating in np.ndenumerate(test_ds.values):

    if rating > 0:
        sim_item_ids = np.argsort(active_item_pearson_corr[j])[-(K + 1):-1]

        # the coefficient values of similar items
        sim_val = active_item_pearson_corr[j][sim_item_ids]

        # the average value of the current item's ratings
        sim_items = imputed_train_ds.T.values[sim_item_ids]
        item_mean = np.sum(active_ds.T.values[j]) / (np.sum(np.clip(active_ds.T.values[j], 0, 1)) + EPSILON)
        sim_item_mean = np.sum(sim_items, axis=1) / (np.sum(np.clip(sim_items, 0, 1), axis=1) + EPSILON)

        # sim(u, v) * (r_v - mean_v)
        sim_r_sum_mean = sim_val * (sim_items[:, i] - sim_item_mean) 

        # filter unrated items
        w = np.clip(sim_items[:, i], 0, 1)
        sim_r_sum_mean *= w

        item_based_pred = item_mean + np.sum(sim_r_sum_mean) / (np.sum(sim_val * w) + EPSILON)    
        item_based_pred = np.clip(item_based_pred, 0, 5)
            
        test_ds_pred[i][j] = item_based_pred
        
test_ds_pred

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [4.10087098, 0.        , 3.86002267, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [4.32319007, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

## Compute MAE and RMSE

In [9]:
# MAE
MAE = np.sum(np.abs(test_ds_pred - test_ds.values)) / np.sum(np.clip(test_ds.values, 0, 1))

# RMSE
RMSE = np.sqrt(np.sum(np.square(test_ds_pred - test_ds.values)) / np.sum(np.clip(test_ds.values, 0, 1)))

print("MAE: {}, RMSE: {}" .format(MAE, RMSE))

MAE: 0.8913854173459005, RMSE: 1.131647448796723